### ISSUE TITLE
Pose Keypoints model?

### ISSUE THREAD

**Issue by mukundhan3** [thmoa/videoavatars#50]
Since you have not provided sample data, there is a doubt on which model to use for Human Pose detection. 
a) Should we only use OpenPose? 
b) If so, should we only use the 25 keypoints model or anything else? (15, 18 etc?)
Your inputs would be greatly helpful for me to try out the framework quickly.

**Comment by JamesBDev** [comment]
Hi
I also have same problem in file videoavatars/prepare_data/2djoints2hdf5.py
Read 54 joint but in Openpose create 75 joint array
And never issue support was useful just close issue and write read paper!!!
And never let's people work on project because they don't want provide Dataset!!! 
I send many mail but just rejected without any reason!!!
I think they put code in Github but they don't want anybody use this code for any research!!!

**Comment by thmoa** [comment]
We provide sample data. Also please read the paper.
